services:
  - name: review-server
    env:
      - key: POSTGRES_URL
        value: jdbc:postgresql://admin:OqTSchvip_ZH-hz7YpYwVs6Wc_Mlij@us-east-1.b52152fa-97a4-4ebb-87be-812fdf65a3b0.aws.ybdb.io:5433/postgres?ssl=true&sslmode=require&sslrootcert=/etc/secrets/root.crt
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: OqTSchvip_ZH-hz7YpYwVs6Wc_Mlij
    buildCommand: mvn clean package
    startCommand: java -jar target/review-service.jar
    ports:
      - port: 8083
        name: http
    healthCheckPath: /actuator/health