services:
  - name: mongodb
    image: mongo:latest
    ports:
      - port: 27017
        name: mongodb
  - name: cozy_home
    env:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATA_MONGODB_URI
        value: "mongodb+srv://user:egy4OdPi4Wyrm99k@cluster0.bgj8zvs.mongodb.net/product_db?retryWrites=true&w=majority"
    buildCommand: mvn clean package
    startCommand: java -jar target/product-service-0.0.1-SNAPSHOT.jar
    ports:
      - port: 8080
        name: http
    healthCheckPath: /actuator/health