services:
  - name: review-service
    buildCommand: docker build -t review-service .
    startCommand: docker run -p 8083:8083 -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=OqTSchvip_ZH-hz7YpYwVs6Wc_Mlij -e POSTGRES_URL=jdbc:postgresql://admin:OqTSchvip_ZH-hz7YpYwVs6Wc_Mlij@us-east-1.b52152fa-97a4-4ebb-87be-812fdf65a3b0.aws.ybdb.io:5433/postgres?ssl=true&sslmode=require&sslrootcert=/etc/secrets/root.crt review-service
